---
language: minimal
services:
- docker

before_script:
- docker build -t builder .

script:
- docker run --rm -v $PWD/dist:/dist -e TRAVIS_BRANCH=$TRAVIS_BRANCH builder

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
