dist: xenial
language: python
cache: pip
sudo: required
services:
- docker

before_script:
- docker build -t builder .

script:
- docker run --rm -v $PWD/dist:/dist builder

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: dist/zeroc*
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: dist/ice*
    skip_cleanup: true
    on:
      tags: true
